### ISSUE TITLE
주제 정하기

### ISSUE THREAD

**Issue by ohoraming** [ohoraming/withMe#1]
### 데이터를 활용한 프로젝트를 계획 중임

흥미로운 데이터나 아이디어 제안하기

**Comment by ohoraming** [comment]
와랏 경남몬!

**Comment by kkn1125** [comment]
경남경남!

**Comment by kkn1125** [comment]
## 주제

- 미정

### 사용 데이터

- [x] 관광데이터
   - [관광지 정보](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15013104 '관광지 정보')
- [ ] 날씨데이터
   - [환경관리공단 API](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15073885 '미세먼지')
   - [관광지 상세 날씨](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15056912 '관광지 상세 날씨')

### UI 형태

1. 대시보드

### 데이터 처리

- [x] json 처리 (방식 결정)
- [ ] 날씨 기상정보 (좋음, 보통, 나쁨 서치)
   - TCI
   - 미세먼지

## 작업

1. UI kimson
2. Data ohoraming

**Comment by kkn1125** [comment]
주제 완료
